import Checkout from "./application/usecase/Checkout";
import AxiosAdapter from "./infra/http/AxiosAdapter";
import CLIController from "./infra/cli/CLIController";
import CLIHandlerNode from "./infra/cli/CLIHandlerNode";
import CouponRepositoryDatabase from "./infra/repository/CouponRepositoryDatabase";
import CurrencyGatewayHttp from "./infra/gateway/CurrencyGatewayHttp";
import MySqlAdapter from "./infra/database/MySqlAdapter";
import OrderRepositoryDatabase from "./infra/repository/OrderRepositoryDatabase";
import ProductRepositoryDatabase from "./infra/repository/ProductRepositoryDatabase";
import FreightGatewayHttp from "./infra/gateway/FreightGatewayHttp";
import CatalogGatewayHttp from "./infra/gateway/CatalogGatewayHttp";
import AuthGatewayHttp from "./infra/gateway/AuthGatewayHttp";
import StockGatewayHttp from "./infra/gateway/StockGatewayHttp";
import RabbitMQAdapter from "./infra/queue/RabbitMQAdapter";

const connection = new MySqlAdapter();
const httpClient = new AxiosAdapter();
const currencyGateway = new CurrencyGatewayHttp(httpClient);
const productRepository = new ProductRepositoryDatabase(connection);
const couponRepository = new CouponRepositoryDatabase(connection);
const orderRepository = new OrderRepositoryDatabase(connection);
const freightGateway = new FreightGatewayHttp(httpClient);
const catalogGateway = new CatalogGatewayHttp(httpClient);
const authGateway = new AuthGatewayHttp(httpClient);
const stockGateway = new StockGatewayHttp(httpClient);
const queue = new RabbitMQAdapter();
// await queue.connect();
const checkout = new Checkout(currencyGateway, productRepository, couponRepository, orderRepository, freightGateway, catalogGateway, authGateway, stockGateway, queue);
const handler = new CLIHandlerNode();
new CLIController(handler, checkout);